apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pendingapi.fullname" . }}
  labels:
    {{- include "pendingapi.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "pendingapi.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "pendingapi.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Values.containers.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: ES_HOST
            values: {{ .Values.containers.es_host }}
          ports:
            - name: http
              containerPort: {{ .Values.containers.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http